server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost


spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: card-service
          uri: lb://card-service
          predicates:
            - Path=/card/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - RemoveRequestHeader=Cookie
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: http://localhost:8180/auth/realms/DHM/protocol/openid-connect/auth
            userinfo-uri: http://localhost:8180/auth/realms/DHM/protocol/openid-connect/userinfo
            user-name-atribute: preferred_username
            token-uri: http://localhost:8180/auth/realms/DHM/protocol/openid-connect/token
        registration:
          dhm-client:
            provider: keycloak
            client-id: dhm-client
            client-secret: dca0cc8c-eb29-45a8-b8d5-f7fba46088e2
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8180/login/oauth2/code/dhm-client